- name: Add key
  hosts: zabbix_monitor
  become: yes
  tasks:

  - name: Set authorized key from file
    authorized_key:
      user: "{{ ansible_ssh_user }}"
      state: present
      key: "{{ lookup('file', './publickey/your.key.pub') }}"
